global:
  scrape_interval: 30s
  external_labels:
    system: quarkus-edac

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: quarkus-applications
    honor_labels: true
    metrics_path: /q/metrics
    static_configs:
      - targets: ['edac-applications:8080']
        labels:
          app: quarkus-applications
          application: quarkus-applications
          system: quarkus-system